version: '2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    container_name: land-filebeat
    privileged: true
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /data/web/app/runtime/logs/buyer:/data/web/app/runtime/logs/buyer #需要扫描的文件夹