version: '2'
services:
    redis:
        image: redis
        ports:
        - 6379:6379
        networks:
        - net-spring-db
        restart: always
networks:
  net-spring-db:
    driver: bridge
