version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8088:80
    networks:
      - net-nginx
    volumes:
      - ~/nginx/www/spring:/usr/share/nginx/html
      - ~/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/logs:/var/log/nginx nginx
networks:
  net-nginx:
    driver: bridge
