version: '3.1'
services:
  jenkins_fan:
    image: jenkins/jenkins:lts
    container_name: jenkins_wis
    restart: always
    ports:
      - 8535:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
volumes:
  data:
    driver: local