version: '2'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    # host name your docker machine ip
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.31.128"
      KAFKA_ZOOKEEPER_CONNECT: 192.168.31.128:2181
    # always restart
    restart: always
    links: 
      - zookeeper
    volumes:
      - ./docker.sock:/var/run/docker.sock